### ISSUE TITLE
Throwing error on loading recipes (modded)

### ISSUE THREAD

**Issue by thetzeestraten** [Rybadour/Foreman#50]
Hi!

I'm getting an error on the recipe loading stage.

I've double checked that the game data folder and mods folder are correct.

Btw I love your work, I've used Foreman before and its easily the best Factorio tool I've come across. The ability to move the flowchart around makes it so much more user friendly and easy to understand, compared to other similar tools.

Oh yeah error text:

I hope it's just me being dumb and not figuring out what I did wrong.

************** Exception Text **************
System.NullReferenceException: Object reference not set to an instance of an object.
   at Foreman.DataCache.ReadModSettings() in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 392
   at Foreman.DataCache.LoadAllData(List`1 enabledMods, CancellableProgress progress) in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 223
   at System.Threading.Tasks.Task.Execute()
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at Foreman.ProgressForm.<ProgressForm_Load>d__4.MoveNext() in E:\Projects\ForemanGit\Foreman\Forms\ProgressForm.cs:line 44
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()

**Comment by ybeauchamph** [comment]
This look like a duplicate of #47 that got fixed but unreleased.

**Comment by thetzeestraten** [comment]
Thanks. I did have a look through but must have missed it.
