### ISSUE TITLE
Crash on load with System.NullReferenceException in 0.18.1

### ISSUE THREAD

**Issue by ryancwilliams** [Rybadour/Foreman#51]
When launching Forman the application crashes with a NullReferenceException.

Here is the output:
> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Foreman.DataCache.ReadModSettings() in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 392
>    at Foreman.DataCache.LoadAllData(List`1 enabledMods, CancellableProgress progress) in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 223
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Foreman.ProgressForm.<ProgressForm_Load>d__4.MoveNext() in E:\Projects\ForemanGit\Foreman\Forms\ProgressForm.cs:line 44
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Foreman
>     Assembly Version: 0.0.1.1
>     Win32 Version: 0.0.0.0
>     CodeBase: file:///C:/Users/Ryan%20Williams/Downloads/Foreman-Release/Foreman.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4300.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> NLua
>     Assembly Version: 1.3.2.0
>     Win32 Version: 1.3.2
>     CodeBase: file:///C:/Users/Ryan%20Williams/Downloads/Foreman-Release/NLua.DLL
> ----------------------------------------
> KeraLua
>     Assembly Version: 1.3.2.0
>     Win32 Version: 1.3.2.0
>     CodeBase: file:///C:/Users/Ryan%20Williams/Downloads/Foreman-Release/KeraLua.DLL
> ----------------------------------------
> Accessibility
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Accessibility/v4.0_4.0.0.0__b03f5f7f11d50a3a/Accessibility.dll
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 10.0.0.0
>     Win32 Version: 10.0.1.20720
>     CodeBase: file:///C:/Users/Ryan%20Williams/Downloads/Foreman-Release/Newtonsoft.Json.DLL
> ----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Dynamic
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.8.4341.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.IO.Compression.FileSystem
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
> ----------------------------------------
> System.IO.Compression
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/WINDOWS/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.

**Comment by King-of-Blades** [comment]
I also get this, as well as the error log being packed full of:

> Mod 'angelsaddons-storage' has malformed dependency '(?) angelsrefining'
> Could not find dependency for Mod 'equipment-gantry'. It requires '?informatron >= 0.2.1'.

for every mod in my list, and they all have their dependencies installed.

**Comment by salihkilic** [comment]
I'm getting the same message. Foreman does load after I get the message, but it shows no recipes.

Message: 

> See the end of this message for details on invoking 
> just-in-time (JIT) debugging instead of this dialog box.
> 
> ************** Exception Text **************
> System.NullReferenceException: Object reference not set to an instance of an object.
>    at Foreman.DataCache.ReadModSettings() in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 392
>    at Foreman.DataCache.LoadAllData(List`1 enabledMods, CancellableProgress progress) in E:\Projects\ForemanGit\Foreman\DataCache.cs:line 223
>    at System.Threading.Tasks.Task.Execute()
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
>    at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
>    at Foreman.ProgressForm.<ProgressForm_Load>d__4.MoveNext() in E:\Projects\ForemanGit\Foreman\Forms\ProgressForm.cs:line 44
> --- End of stack trace from previous location where exception was thrown ---
>    at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
> 
> 
> ************** Loaded Assemblies **************
> mscorlib
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.NET/Framework64/v4.0.30319/mscorlib.dll
> ----------------------------------------
> Foreman
>     Assembly Version: 0.0.1.1
>     Win32 Version: 0.0.0.0
>     CodeBase: file:///C:/Users/Equinox/Downloads/Release/Foreman.exe
> ----------------------------------------
> System.Windows.Forms
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4400.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Windows.Forms/v4.0_4.0.0.0__b77a5c561934e089/System.Windows.Forms.dll
> ----------------------------------------
> System
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4360.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System/v4.0_4.0.0.0__b77a5c561934e089/System.dll
> ----------------------------------------
> System.Drawing
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Drawing/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Drawing.dll
> ----------------------------------------
> System.Configuration
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4190.0 built by: NET48REL1LAST_B
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Configuration/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Configuration.dll
> ----------------------------------------
> System.Core
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4390.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Core/v4.0_4.0.0.0__b77a5c561934e089/System.Core.dll
> ----------------------------------------
> System.Xml
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Xml/v4.0_4.0.0.0__b77a5c561934e089/System.Xml.dll
> ----------------------------------------
> NLua
>     Assembly Version: 1.3.2.0
>     Win32 Version: 1.3.2
>     CodeBase: file:///C:/Users/Equinox/Downloads/Release/NLua.DLL
> ----------------------------------------
> KeraLua
>     Assembly Version: 1.3.2.0
>     Win32 Version: 1.3.2.0
>     CodeBase: file:///C:/Users/Equinox/Downloads/Release/KeraLua.DLL
> ----------------------------------------
> Newtonsoft.Json
>     Assembly Version: 10.0.0.0
>     Win32 Version: 10.0.1.20720
>     CodeBase: file:///C:/Users/Equinox/Downloads/Release/Newtonsoft.Json.DLL
> ----------------------------------------
> Microsoft.CSharp
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/Microsoft.CSharp/v4.0_4.0.0.0__b03f5f7f11d50a3a/Microsoft.CSharp.dll
> ----------------------------------------
> System.Numerics
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0 built by: NET48REL1
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Numerics/v4.0_4.0.0.0__b77a5c561934e089/System.Numerics.dll
> ----------------------------------------
> System.Dynamic
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Dynamic/v4.0_4.0.0.0__b03f5f7f11d50a3a/System.Dynamic.dll
> ----------------------------------------
> Anonymously Hosted DynamicMethods Assembly
>     Assembly Version: 0.0.0.0
>     Win32 Version: 4.8.4420.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/mscorlib/v4.0_4.0.0.0__b77a5c561934e089/mscorlib.dll
> ----------------------------------------
> System.Data
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4270.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_64/System.Data/v4.0_4.0.0.0__b77a5c561934e089/System.Data.dll
> ----------------------------------------
> System.Runtime.Serialization
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4250.0 built by: NET48REL1LAST_C
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.Runtime.Serialization/v4.0_4.0.0.0__b77a5c561934e089/System.Runtime.Serialization.dll
> ----------------------------------------
> System.IO.Compression.FileSystem
>     Assembly Version: 4.0.0.0
>     Win32 Version: 4.8.4084.0
>     CodeBase: file:///C:/Windows/Microsoft.Net/assembly/GAC_MSIL/System.IO.Compression.FileSystem/v4.0_4.0.0.0__b77a5c561934e089/System.IO.Compression.FileSystem.dll
> ----------------------------------------
> 
> ************** JIT Debugging **************
> To enable just-in-time (JIT) debugging, the .config file for this
> application or computer (machine.config) must have the
> jitDebugging value set in the system.windows.forms section.
> The application must also be compiled with debugging
> enabled.
> 
> For example:
> 
> <configuration>
>     <system.windows.forms jitDebugging="true" />
> </configuration>
> 
> When JIT debugging is enabled, any unhandled exception
> will be sent to the JIT debugger registered on the computer
> rather than be handled by this dialog box.
